name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          deno-version: canary
      - uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: lint
        if: runner.os == 'Linux'
        run: |
          deno lint
          deno doc --lint mod.ts

      - name: Deno tests
        run: deno test -A

      - name: Node tests
        run: npx deno-test@1.0.3

  publish:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          deno-version: canary
      - name: Publish to JSR on tag
        if: runner.os == 'Linux'
        run: deno run -A jsr:@david/publish-on-tag@0.2.0
